### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by mksaleem** [varmd/wine-wayland#68] opened 2023-02-27 19:07 UTC
It is possible to use it on Fedora or under Lutris?

**Comment by Lyamc** [comment] 2023-03-05 23:00
Fedora and Lutris are two very different things.

Regarding Fedora, this is a duplicate of #54, and you have three options:
1. Build it manually from source, using the PKGBUILD as a sort of a template.
2. Use something like this https://github.com/makedeb/makedeb to take the PKGBUILD and spit out a .deb and then `sudo yum install alien` to convert that into .rpm or whatever.
3. Use Arch.

If you create a working script that works well on another distro, then you can always share it here or submit a PR.

You'll likely have trouble with getting it to play nicely with Lutris unless you make a Lutris script yourself.

**Comment by mksaleem** [comment] 2023-03-10 16:26
Thank you for the reply, I am not really that good with Linux. I wish I was :)

**Comment by IsaacFehr** [comment] 2023-03-27 21:54
+1 to fedora support!  I'll play around any see if I can get this to work

**Comment by mksaleem** [comment] 2023-03-28 00:07
> +1 to fedora support! I'll play around any see if I can get this to work

That would be great, I hope you get it working

**Closed** 2024-03-02 09:22 UTC
