### ISSUE TITLE
Other distros

### ISSUE THREAD

**Issue by VarLad** [varmd/wine-wayland#46] opened 2021-11-11 19:52 UTC
Any plans to add instructions on how to run this on other distros as well?

**Comment by yunginnanet** [comment] 2021-12-01 00:35
Yeah fr, this is **racist**.

<details>
<summary>Long rant about arch users</summary>
/s
</details>

**Comment by varmd** [comment] 2021-12-16 16:26
I don't use other distros, so can't add instructions. Tested PRs can be added. Also, duplicate of #8.

**Closed by varmd** 2021-12-16 16:26 UTC
